### ISSUE TITLE
adding support for LD series cooler

### ISSUE THREAD

**Issue by asdfzdfj** [Nortank12/deepcool-digital-linux#1]
based on my work in https://github.com/asdfzdfj/deepcool-ld-digital-hidapi

continuation of https://github.com/asdfzdfj/deepcool-ld-digital-hidapi/issues/1 as this has more to do with your repo/project than mine

**Comment by Nortank12** [comment]
After staring at your code for a while, I have some questions:
- do you have LD240 or LD360?
  - from other repos I could confirm that the PID 10 refers to "LD-Series" on LD240 and I want to make sure it's the same for LD360
- can you write me in detail what each segment of the packet is used for and what the init sequence does exactly?

I want to make sure I understand every step of the process before I try to replicate it.

**Comment by asdfzdfj** [comment]
> do you have LD240 or LD360? 

I have only LD240 so no new datapoints here, sorry. 
though I think there's a good chance it'll work with LD360 also (it's quite likely that the only main difference is just the radiator size while the water block assembly (which have the display) remains the same)

---

> can you write me in detail what each segment of the packet is used for and what the init sequence does exactly?

## overview

overall packet structure contains:
- variable numbers of data bytes
- followed by a checksum byte (just sum all the data bytes together then take the last byte from the results)
- terminated (?) by a constant value `22`, after the checksum byte

report ID (`REPORT_ID`) for all packets sent: `16`

*NOTE: the leading `REPORT_ID` byte is omitted here as that's how hidapi does things rather than being part of the data sent*

## init sequence packets

- first packet: `[104, 1, 1, 2, 3, 1, 112, 22]`  
  this seems to trigger the starting animation for a bit before bringing up the display
  
  [ld240-startup.webm](https://github.com/user-attachments/assets/d3a8bd7e-3057-4829-b998-47ac9c9eae39)

- second packet: `[104, 1, 1, 2, 2, 1, 111, 22]`
  I dont know what this does either, it just brings up the display without the startup animation (though I guess any packet sent would at least result in this same thing)

## data report packet

```text
[
    104, 1, 1, 11, 1, 2, 5,
    p1, p0,
    use_fahrenheit,
    t3, t2, t1, t0,
    u0,
    checksum,
    22
]
```

- `104, 1, 1, 11, 1, 2, 5`: essentially magic numbers, probably packet preamble?
- `p1, p0`: `u16` int bytes indicate cpu power usage, MSB first
- `use_fahrenheit`: single `u8` byte
  - set to `0` to use celsius unit display segment
  - set to `1` (or perhaps any non-zero) to use fahrenheit unit display segment (you still have to do the temperature conversion yourself though)
- `t3, t2, t1, t0`: IEEE 754 `f32` float bytes indicating temperature, MSB first
  - probably shouldn't send `NaN`s to this thing
  - fahrenheit conversion is done on software side before sending the results through this value here
- `u0`: single `u8` byte indicating cpu usage percent
  - should probably be capped to `[0, 100]` range before sending
- the usual checksum and terminating byte, as described in the overview section above

**Comment by Nortank12** [comment]
Appreciated!

I uploaded the code to the `ld-series` branch. It will display the datastream being sent to the device.

There are two things I'd note:
- If you want to do a test run without writing any data to your device, you can comment [Line 138](https://github.com/Nortank12/deepcool-digital-linux/blob/e9dd0440ea59832e6ad362e39d31bddbb0ed1a56/src/main.rs#L138)
- I'm not sure if you need to wait for the init sequence to finish, so please add a delay below [Line 81](https://github.com/Nortank12/deepcool-digital-linux/blob/e9dd0440ea59832e6ad362e39d31bddbb0ed1a56/src/main.rs#L81) if necessary

In case you need a binary, let me know, and I'll upload a pre-release for you.

**Comment by asdfzdfj** [comment]
initial results: the new code can successfully send data to the device for display

though I edited the test code a bit to have it sent some fixed values instead of the system metric as the testing system's still on freebsd, so none of the linux targeted metric collector would work, but I trust that those collector should work fine

[ld-series-cycle.webm](https://github.com/user-attachments/assets/816afff1-f8f2-4872-8b2b-b360c25de586)

some notes: the display update rate seems to be at most once per second, sending update report faster than that might make the display not look like how one would expect (didn't look too close at what's really happened but it looks like the display chose to display last received value, rather than delayed value display as if the reports are stuck waiting in a queue)

**Comment by Nortank12** [comment]
Yes, on the AK series, the alarm can be enabled or disabled manually. I will write the instructions accordingly.

Can you test the next release binary on Linux? It should work on any distro even on USB boot. If you can confirm that it works, I will close this issue and mark the LD240 as tested.

It will take 1-2 days to make it, I will let you know.

**Comment by asdfzdfj** [comment]
here's it running on a real Linux system

[ld-series-linux.webm](https://github.com/user-attachments/assets/a661ce4c-4c2c-4a06-a421-9c7b6150db10)

note that the clip was from another run where I built the binary myself with `cargo build --release` from the tag (console only system, typing repo url for `git clone` is easier than typing binary download link when doing it by hand), tried again with binary downloaded from release and it still works + behaves the same

**Comment by Nortank12** [comment]
Perfect! Thank you for your help. I have found someone on reddit who has the LD360 so we can confirm the compatibility soon.

I've added your repo in the Development section.
