### ISSUE TITLE
LS720-SE-DIGITAL-WH - Device not yet supported

### ISSUE THREAD

**Issue by FlyingYu-Z** [Nortank12/deepcool-digital-linux#11]
Vendor ID: 13875
Device ID: 6
Vendor name: DeepCool
Device name: LS-SE-DIGITAL

**Comment by Nortank12** [comment]
Hey there!
Are you the same person who [commented](https://www.reddit.com/r/linux_gaming/comments/1djpz73/comment/lsutrth/) on Reddit?

**Comment by FlyingYu-Z** [comment]
solved in this PR: https://github.com/Nortank12/deepcool-digital-linux/pull/12

**Comment by FlyingYu-Z** [comment]
> Hey there! Are you the same person who [commented](https://www.reddit.com/r/linux_gaming/comments/1djpz73/comment/lsutrth/) on Reddit?

No,It's not me.
