### ISSUE TITLE
Latest Nvidia library (565.57.01) on Debian 12 (bookworm)

### ISSUE THREAD

**Issue by Jurriaan-BlueGen** [Nortank12/deepcool-digital-linux#20]
I ran into a minor issue on a Debian 12 (bookworm) install, with the Nvidia drivers directly from Nvidia: 
the _libnvidia-ml.so_ link was missing, and there was only a _.so.1_ version.

This caused the "NVIDIA GPU library was not found" error to be shown.

I created the .so link by hand, and now everything works again.

I'm not super experienced with what the correct way to handle this would be, but just wanted to give a heads-up and possibly help out is someone else runs into this issue.

Thanks for the work on this project! Really appreciate the effort.

**Comment by Nortank12** [comment]
I've looked up your issue, and it seems like on Debian there's only a `libnvidia-ml.so.1`. On Arch there are `libnvidia-ml.so` and `libnvidia-ml.so.1`, both of which point to the latest driver (`libnvidia-ml.so.565.57.01` in my case).

I've included additional paths with `.so.1` endings for all known locations.

Thank you for noticing!
