### ISSUE TITLE
AG 400 Digital - Device not yet supported

### ISSUE THREAD

**Issue by jeronimobs** [Nortank12/deepcool-digital-linux#3]
Hi! I've tried it on my debian 12 resulting the following:

Device found: AG-DIGITAL
-----
Device not yet supported!

Vendor ID: 13875
Device ID: 8
Vendor name: DeepCool
Device name: AG-DIGITAL

Here is the product page:
https://www.deepcool.com/products/Cooling/cpuaircoolers/AG400-DIGITAL-Temperature-Display-Cooler-1700-AM5/2023/17686.shtml

**Comment by Nortank12** [comment]
Hey!

Seems like the AG series are very similar to the AK series, so I used it as a baseline.

Modifications:
- Removed ˚F
- Removed green progress bar
- Removed DIGIT 1 (using DIGIT 2 and DIGIT 3)
- Lowered the alarm temp. to 45˚C (for testing)

If we get lucky it should display something. If we get extremely lucky, it will work on the first try. I have some concerns that the values might be a little offset because now it's sending zeroes on index 2 (progress bar) and 3 (digit 1).
I will create a new branch and a pre-release soon so you can test it.

**Comment by Nortank12** [comment]
[Here](https://github.com/Nortank12/deepcool-digital-linux/releases/tag/v0.2.2-pre-alpha) is the release.

**Comment by jeronimobs** [comment]
Hello! Had some time to test it! It shows either 04 ou 05 celsius at the
mini display and flickers here and there.

At the terminal:

Device found: AG-DIGITAL
-----
DISP. MODE: temp
TEMP. UNIT: ˚C (˚F not supported)
ALARM:      off
-----
Update interval: 750ms

 IMG_0981.MOV
<https://drive.google.com/file/d/1zk7ZcVspqYuGx9_pS-CiNlNW_yMg9VCQ/view?usp=drive_web>

**Comment by Nortank12** [comment]
Very interesting. I have a theory what might cause the issue.
If you have 49˚C and the values are offset, that means you get [0, 4, 9] and it sends 9 to the alarm. When you have 50˚C you get [0, 5, 0] meaning alarm gets 0 so it stops flickering. I'll offset the temp and alarm by 1 and it should work.

I'll create a new version soon.

**Comment by Nortank12** [comment]
I have modified the existing release so you can download it from [the same link](https://github.com/Nortank12/deepcool-digital-linux/releases/tag/v0.2.2-pre-alpha).
If it works right away, I'd ask you to test the following:
- `-m usage` for displaying usage. If you don't have a tool, you can use [this site](https://cpux.net/cpu-stress-test-online) to give it a 100% load. The value on the cooler should be capped at 99.
- `-a` for the alarm. I left the value at `45˚C` so it should only flicker at or above that.

**Comment by jeronimobs** [comment]
Hey! It worked! :)

Also did both of the requested tests. Both are to be considered as
successfull.
Thou the usage one i could not bring up the load to a 100%, i used
handbreak to convert videos using the CPU. Can confirm that all went
correctly.

Let me know if you need any more tests or usage informations.
 IMG_0982.mp4
<https://drive.google.com/file/d/1YdV8HMTWt4U_e3yMDIUNL1yM5wiWAguX/view?usp=drive_web>
 IMG_0984.mp4
<https://drive.google.com/file/d/1D3oTuY86vItEunIZcUoZNlKbEyevdo5N/view?usp=drive_web>

**Comment by Nortank12** [comment]
Perfect, thank you for your help! I added the code to the main version.
