### ISSUE TITLE
MORPHEUS/AMD Test Results

### ISSUE THREAD

**Issue by jackalyst** [Nortank12/deepcool-digital-linux#5]
System

```
Linux Distribution:		Fedora Linux 40 (Workstation Edition)
Linux Kernel:			6.10.3-200.fc40.x86_64
Computer Model:			Gigabyte Technology Co., Ltd. X570S AORUS MASTER -CF
Processor (CPU):		AMD Ryzen 9 5950X 16-Core Processor
Architecture:			x86_64 (64-bit)
Graphics Processor (GPU): Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] (rev c1)
```

The v0.4.0-alpha binary fails on my machine with the error message "AMD PCI data not found". When I pointed it directly to my device at `/sys/devices/pci0000:00/0000:00:03.1/0000:0a:00.0/0000:0b:00.0/0000:0c:00.0/gpu_busy_percent` it seems to work in both usage and temperature modes. I suspect if it didn't exit, the temperature sensor would likely work. 

I can try an NVIDIA card on the weekend but at least I'd consider the display output as working so can probably check off that box. "Just" picking up device and sensor data is problematic.

Nice work.

**Comment by Nortank12** [comment]
Thank you for the info! I have changed the device lookup, so it checks the whole folder now. Can you check on it before I create a new release?

And about the MORPHEUS. I forgot to add the startup animation to the second progress bar. Can you confirm that the animation is visible only on the CPU display?

**Comment by jackalyst** [comment]
It seems the new AMD PCI device detection was successful! Additionally, for MORPHEUS, both the GPU and CPU appear to have startup animations, and not just one side.

I didn't get to testing the NVIDIA card, but I'll make another issue if there's an issue there.
